version: '3.3'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: pg_stack_promentheus
    volumes:
      - "./resources/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - pg_stack_prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      # - "-storage.local.path=/prometheus"
    ports:
      - '9090:9090'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: pg_stack_node_exporter
    ports:
      - '9100:9100'

  grafana:
    image: grafana/grafana:latest
    container_name: pg_stack_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus
    volumes:
      - "./resources/config/grafana/provisioning:/etc/grafana/provisioning:ro"
      - pg_stack_grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  pg_stack_prometheus_data:
  pg_stack_grafana_data:
