global:
  scrape_interval: 5s
  external_labels:
    monitor: 'pg_stack'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-information'
    scrape_interval: 5s
    static_configs:
      - targets: ['rinzler:9100', 'hal:9100', 'tron:9100', 'kobol:9100']
        labels:
          group: "node-metrics"
      - targets: ['rinzler:9110', 'hal:9110', 'tron:9110', 'kobol:9110']
        labels:
          group: "docker-metrics"
  - job_name: 'blackbox-portainer'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "http://kobol:9990"
        - "http://hal:9990"
        - "http://rinzler:9990"
        - "http://tron:9990"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pg_stack_blackbox_exporter:9115  # Container Name
