global:
  scrape_interval: 5s
  external_labels:
    monitor: 'pg_stack'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  ##############################################################################
  #    node exporter                                                           #
  ##############################################################################
  - job_name: 'node-information'
    scrape_interval: 5s
    static_configs:
      - targets: ['kobol:9100', 'prometheus:9100', 'k8s-master:9100', 'k8s-worker-1:9100', 'k8s-worker-2:9100', 'garfield:9100']
        labels:
          group: "node-metrics"
      - targets: ['kobol:9110', 'prometheus:9110', 'k8s-master:9110', 'k8s-worker-1:9110', 'k8s-worker-2:9110', 'garfield:9110']
        labels:
          group: "docker-metrics"
  ##############################################################################
  #    blackbox exporter                                                       #
  ##############################################################################
  - job_name: 'blackbox-portainer'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "http://kobol:9990"
        - "http://prometheus:9990"
        - "http://k8s-master:9990"
        - "http://k8s-worker-1:9990"
        - "http://k8s-worker-2:9990"
        - "http://garfield:9990"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
  - job_name: 'blackbox-jenkins'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - "http://k8s-master:9080"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
