global:
  scrape_interval: 5s
  external_labels:
    monitor: 'pg_stack'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      # - targets: ['node-exporter:9100']
      - targets: ['rinzler:9100', 'hal:9100', 'tron:9100', 'kobol:9100']
  - job_name: 'docker-metrics'
    static_configs:
      - targets: ['rinzler:9417', 'hal:9417', 'tron:9417', 'kobol:9417']
