global:
  scrape_interval: 5s
  external_labels:
    monitor: 'pg_stack'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      # - targets: ['node-exporter:9100']
      - targets: ['rinzler:9100', 'hal:9100', 'tron:9100', 'kobol:9100']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['rinzler:9110', 'hal:9110', 'tron:9110', 'kobol:9110']
