version: "3.3"
services:

################################################################################
#    prometheus + grafana                                                      #
################################################################################

  prometheus:
    image: prom/prometheus:latest
    container_name: promentheus
    restart: unless-stopped
    volumes:
      - "./resources/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - pg_stack_prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      # - "-storage.local.path=/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - F_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus
    volumes:
      - "./resources/provisioning/grafana:/etc/grafana/provisioning:ro"
      - pg_stack_grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - "./resources/config/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml:ro"
    command:
      - "--config.file=/etc/prometheus/blackbox-exporter.yml"

volumes:
  pg_stack_prometheus_data:
  pg_stack_grafana_data:
